ws_url: ws://localhost:7880
api_key: devkey
api_secret: supersecureyoursecretkeywith32chars!!

redis:
  address: localhost:6379

sip_port: 5070
rtp_port: 10000-60000
use_external_ip: true

