ws_url: ws://host.docker.internal:7880
api_key: devkey
api_secret: supersecureyoursecretkeywith32chars!!

redis:
  address: "host.docker.internal:6379"
  
      
sip_port: 5060
rtp_port: 10000-60000
use_external_ip: true
logging:
  level: debug